# Generated by Django 5.2.4 on 2026-03-02 09:35

import accounts.models
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(default=accounts.models.generate_account_number, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('fixed_deposit', 'Fixed Deposit'), ('salary', 'Salary Account')], default='savings', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed'), ('pending', 'Pending Activation')], default='active', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('3.50'), max_digits=5)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(default='NexaBank', max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'beneficiaries',
                'ordering': ['beneficiary_name'],
            },
        ),
    ]
