# Generated by Django 5.2.4 on 2026-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='bank_name',
            field=models.CharField(default='CapitalSphere', max_length=100),
        ),
    ]
