# Generated by Django 5.2.4 on 2026-03-02 09:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='upcoming', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emi_schedule',
                'ordering': ['emi_number'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('home', 'Home Loan'), ('car', 'Car Loan'), ('education', 'Education Loan'), ('business', 'Business Loan')], max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('10000'))])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tenure_months', models.IntegerField(help_text='Loan tenure in months', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(360)])),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursement_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_disbursements', to='accounts.account')),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
