# Generated by Django 5.2.4 on 2026-03-02 09:35

import django.db.models.deletion
import transactions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('fee', 'Fee')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reference_number', models.CharField(default=transactions.models.generate_reference, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sender_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('receiver_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='accounts.account')),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender_account', '-created_at'], name='transaction_sender__b235a2_idx'), models.Index(fields=['receiver_account', '-created_at'], name='transaction_receive_df1b11_idx'), models.Index(fields=['reference_number'], name='transaction_referen_dda4a8_idx')],
            },
        ),
    ]
