# Generated by Django 5.2.4 on 2026-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('food', 'Food & Dining'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('travel', 'Travel'), ('education', 'Education'), ('health', 'Health & Fitness'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
