# Generated by Django 5.2.4 on 2026-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('loan_officer', 'Loan Officer')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
