# Generated by Django 5.2.4 on 2026-03-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog_kycdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('transfer', 'Fund Transfer'), ('deposit', 'Self Deposit'), ('pin_change', 'PIN Change'), ('pwd_change', 'Password Change'), ('account_creation', 'Account Creation'), ('beneficiary_addition', 'Beneficiary Addition'), ('beneficiary_removal', 'Beneficiary Removal'), ('loan_application', 'Loan Application'), ('loan_review', 'Loan Review'), ('kyc_upload', 'KYC Upload'), ('admin_deposit', 'Admin Deposit')], max_length=50),
        ),
    ]
